# Generated by Django 3.0.8 on 2020-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=40)),
                ('rating', models.CharField(db_index=True, max_length=50)),
                ('year', models.CharField(db_index=True, max_length=50)),
                ('size', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('image', models.ImageField(upload_to='book_image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=40)),
                ('image', models.ImageField(upload_to='book_image')),
            ],
        ),
    ]
