# Generated by Django 3.0.8 on 2020-07-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=40)),
                ('rating', models.CharField(db_index=True, max_length=50)),
                ('year', models.CharField(db_index=True, max_length=50)),
                ('size', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('image', models.ImageField(upload_to='book_image')),
                ('link', models.CharField(db_index=True, default='image', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=40)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='book_image')),
                ('link', models.CharField(db_index=True, default='image', max_length=150)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='main.Category')),
            ],
        ),
    ]
