# Generated by Django 3.0.8 on 2020-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
    ]
